package dto

type BSPlayersFPLResponseDto struct {
	Minutes                          int     `json:"minutes"`
	GoalsScored                      int     `json:"goals_scored"`
	Assists                          int     `json:"assists"`
	CleanSheets                      int     `json:"clean_sheets"`
	GoalsConceded                    int     `json:"goals_conceded"`
	OwnGoals                         int     `json:"own_goals"`
	PenaltiesSaved                   int     `json:"penalties_saved"`
	PenaltiesMissed                  int     `json:"penalties_missed"`
	YellowCards                      int     `json:"yellow_cards"`
	RedCards                         int     `json:"red_cards"`
	Saves                            int     `json:"saves"`
	Bonus                            int     `json:"bonus"`
	BPS                              int     `json:"bps"`
	Influence                        string  `json:"influence"`
	Creativity                       string  `json:"creativity"`
	Threat                           string  `json:"threat"`
	ICTIndex                         string  `json:"ict_index"`
	Starts                           int     `json:"starts"`
	ExpectedGoals                    string  `json:"expected_goals"`
	ExpectedAssists                  string  `json:"expected_assists"`
	ExpectedGoalInvolvements         string  `json:"expected_goal_involvements"`
	ExpectedGoalsConceded            string  `json:"expected_goals_conceded"`
	TotalPoints                      int     `json:"total_points"`
	InDreamteam                      bool    `json:"in_dreamteam"`
	InfluenceRank                    int     `json:"influence_rank"`
	InfluenceRankType                int     `json:"influence_rank_type"`
	CreativityRank                   int     `json:"creativity_rank"`
	CreativityRankType               int     `json:"creativity_rank_type"`
	ThreatRank                       int     `json:"threat_rank"`
	ThreatRankType                   int     `json:"threat_rank_type"`
	ICTIndexRank                     int     `json:"ict_index_rank"`
	ICTIndexRankType                 int     `json:"ict_index_rank_type"`
	CornersAndIndirectFreekicksOrder *int    `json:"corners_and_indirect_freekicks_order"`
	CornersAndIndirectFreekicksText  string  `json:"corners_and_indirect_freekicks_text"`
	DirectFreekicksOrder             *int    `json:"direct_freekicks_order"`
	DirectFreekicksText              string  `json:"direct_freekicks_text"`
	PenaltiesOrder                   int     `json:"penalties_order"`
	PenaltiesText                    string  `json:"penalties_text"`
	ExpectedGoalsPer90               float64 `json:"expected_goals_per_90"`
	SavesPer90                       float64 `json:"saves_per_90"`
	ExpectedAssistsPer90             float64 `json:"expected_assists_per_90"`
	ExpectedGoalInvolvementsPer90    float64 `json:"expected_goal_involvements_per_90"`
	ExpectedGoalsConcededPer90       float64 `json:"expected_goals_conceded_per_90"`
	GoalsConcededPer90               float64 `json:"goals_conceded_per_90"`
	NowCostRank                      int     `json:"now_cost_rank"`
	NowCostRankType                  int     `json:"now_cost_rank_type"`
	FormRank                         int     `json:"form_rank"`
	FormRankType                     int     `json:"form_rank_type"`
	PointsPerGameRank                int     `json:"points_per_game_rank"`
	PointsPerGameRankType            int     `json:"points_per_game_rank_type"`
	SelectedRank                     int     `json:"selected_rank"`
	SelectedRankType                 int     `json:"selected_rank_type"`
	StartsPer90                      float64 `json:"starts_per_90"`
	CleanSheetsPer90                 float64 `json:"clean_sheets_per_90"`
	ChanceOfPlayingNextRound         *int    `json:"chance_of_playing_next_round"`
	ChanceOfPlayingThisRound         *int    `json:"chance_of_playing_this_round"`
	Code                             int     `json:"code"`
	CostChangeGameweek               int     `json:"cost_change_event"`
	CostChangeGameweekFall           int     `json:"cost_change_event_fall"`
	CostChangeStart                  int     `json:"cost_change_start"`
	CostChangeStartFall              int     `json:"cost_change_start_fall"`
	DreamteamCount                   int     `json:"dreamteam_count"`
	PlayerType                       int     `json:"element_type"`
	EpNext                           string  `json:"ep_next"`
	EpThis                           string  `json:"ep_this"`
	GameweekPoints                   int     `json:"event_points"`
	FirstName                        string  `json:"first_name"`
	Form                             string  `json:"form"`
	ID                               int     `json:"id"`
	News                             string  `json:"news"`
	NewsAdded                        *string `json:"news_added"`
	NowCost                          int     `json:"now_cost"`
	Photo                            string  `json:"photo"`
	PointsPerGame                    string  `json:"points_per_game"`
	SecondName                       string  `json:"second_name"`
	SelectedByPercent                string  `json:"selected_by_percent"`
	Special                          bool    `json:"special"`
	SquadNumber                      *int    `json:"squad_number"`
	Status                           string  `json:"status"`
	Team                             int     `json:"team"`
	TeamCode                         int     `json:"team_code"`
	TransfersIn                      int     `json:"transfers_in"`
	TransfersOut                     int     `json:"transfers_out"`
	TransfersInGameweek              int     `json:"transfers_in_event"`
	TransfersOutGameweek             int     `json:"transfers_out_event"`
	ValueForm                        string  `json:"value_form"`
	ValueSeason                      string  `json:"value_season"`
	WebName                          string  `json:"web_name"`
}
